// Tooltips for the debug panel, keyed by config path. Per-cap, per-light and
// per-can-size values use `*` for the name (CAPS.*.strength); [x, y, z]
// values share one hint (WALL_HAND.aim). DAYLIGHT keys reuse the ATMOS hint.

const HINTS: Record<string, string> = {
  // Movement
  'PLAYER.walkSpeed': 'Top speed when walking (m/s).',
  'PLAYER.sprintSpeed': 'Top speed while holding Shift and moving forward (m/s).',
  'PLAYER.crouchSpeed': 'Top speed while crouched (m/s).',
  'PLAYER.acceleration': 'How quickly you reach the wished speed on the ground or a ladder. Higher = snappier starts and turns.',
  'PLAYER.friction': 'How quickly you stop on the ground when you let go of the keys. Higher = shorter slide.',
  'PLAYER.airControl': 'Fraction of acceleration available in the air. 0 = no steering mid-jump, 1 = full control.',
  'PLAYER.jumpHeight': 'Height of a standing jump (m). The railings are 1.1 m tall.',
  'PLAYER.gravity': 'Downward acceleration (m/s²). Higher = snappier, shorter jumps.',
  'PLAYER.climbSpeed': 'Speed up and down ladders (m/s), including sliding down when you let go.',
  'PLAYER.stepHeight': 'Tallest ledge you walk up without jumping (m).',
  'PLAYER.crouchHeight': 'Collider height while crouched (m): what you can crawl under.',
  'PLAYER.ladderJumpOff': 'How hard Space pushes you away from a ladder (m/s).',
  'PICKUP.radius': 'Walk within this distance of a pickup to collect it (m).',
  'PICKUP.hover': 'How high pickups float above the ground (m).',
  'PICKUP.spin': 'Pickup spin speed (rad/s).',
  'PICKUP.bob': 'How far pickups bob up and down (m).',
  // Camera
  'PLAYER.eyeHeight': 'Camera height above the feet when standing (m).',
  'PLAYER.crouchEyeHeight': 'Camera height above the feet when crouched (m).',
  'PLAYER.crouchTransition': 'How fast the camera moves between standing and crouched heights. Higher = quicker.',
  'PLAYER.stepSmoothing': 'How fast the camera catches up after stepping up or down stairs. Higher = less smoothing.',
  'PLAYER.mouseSensitivity': 'Radians of turn per pixel of mouse movement.',
  'RENDER.fov': 'Vertical field of view (degrees).',
  'RENDER.sprintFovBoost': 'Extra field of view while sprinting (degrees).',
  'RENDER.sprintFovEase': 'How fast the sprint FOV change eases in and out.',
  // Hands
  'VIEWMODEL.swayAmount': 'How far the hands lag behind when you look around.',
  'VIEWMODEL.swayMax': 'Largest lag angle (rad).',
  'VIEWMODEL.swayReturn': 'How fast the hands settle back after looking around.',
  'VIEWMODEL.bobAmount': 'Hand bob while walking, in meters at walking speed.',
  'VIEWMODEL.bobFrequency': 'Bob steps per meter walked.',
  'VIEWMODEL.fallLag': 'Hands dip while rising and lift while falling, per m/s of vertical speed.',
  'VIEWMODEL.pressCurl': 'How far the index finger curls when pressing the nozzle (rad).',
  'VIEWMODEL.pressSpeed': 'How fast the finger presses and releases.',
  // Left hand
  'WALL_HAND.reach': 'The left hand reaches for a wall closer than this to your shoulder (m).',
  'WALL_HAND.release': 'The left hand lets go when the wall is farther than this from your shoulder (m). Keep above reach.',
  'WALL_HAND.speed': 'How fast the left hand moves to the wall and back.',
  'WALL_HAND.slide': 'Re-place the hand when its spot on the wall drifts this far (m). Lower = follows you more closely.',
  'WALL_HAND.fromAngle': 'The hand looks for walls in a fan to your left, starting this many degrees left of where you look (0 = straight ahead).',
  'WALL_HAND.toAngle': 'End of the fan, degrees to the left (90 = your left side, more = behind you).',
  'WALL_HAND.drop': 'Height of the hand (and of the wall search) below the eyes (m).',
  'WALL_HAND.fingerLean': 'How much the fingers lean inward with the palm on the wall (rad).',
  'WALL_HAND.gap': 'Distance between palm and wall (m), to avoid clipping.',
  'WALL_HAND.restOffset': 'Where the hand comes in from and goes back to, relative to the camera (m; x right, y up, -z forward). Keep it out of view: the hand is hidden there.',
  'WALL_HAND.restRotation': 'Rotation of the hand where it comes in from (rad, around x / y / z).',
  'WALL_HAND.restWristBend': 'Wrist bend on the way to the wall and back (rad; negative bends back).',
  'WALL_HAND.wallWristBend': 'Wrist bend with the palm on a wall (rad; negative bends back).',
  // Painting
  'SPRAY.range': 'Farthest distance spray paint reaches (m).',
  'SPRAY.falloffStart': 'Paint is full strength up to this distance, then fades out toward the range (m).',
  'SPRAY.particleSpeed': 'Flight speed of the visible spray particles (m/s). Paint lands when they arrive.',
  'PAINT.alphaSteps': 'Paint opacity is shown in this many steps for a chunky look. 0 = smooth.',
  'MARKER.reach': 'Farthest distance the marker draws (m).',
  'MARKER.radius': 'Marker line radius (m). 0 = one paint texel: the thinnest line the paint detail allows (4 cm on LOW, 1 cm on ULTRA).',
  'MARKER.strength': 'Marker line opacity per stroke.',
  'MARKER.holdDistance': 'How far in front of the eye the marker is held (m).',
  'MARKER.holdScale': 'Size of the held marker and hand.',
  'DRIPS.enabled': 'Paint runs: spraying heavily onto opaque paint on vertical faces makes it run down.',
  'DRIPS.excess': 'Extra coats of paint a spot needs before it may run. Higher = fewer runs.',
  'DRIPS.perSquareMeter': 'Runs that start per square meter of paint reaching the limit. Higher = more runs.',
  'DRIPS.maxActive': 'Most runs moving at the same time, level-wide.',
  'DRIPS.minLength': 'Shortest run (m).',
  'DRIPS.maxLength': 'Longest run (m).',
  'DRIPS.speed': 'Starting speed of a run (m/s). Runs slow down as they go.',
  'DRIPS.strength': 'Opacity of the trail a run leaves.',
  'CAPS.*.strength': 'Opacity each particle adds where it lands.',
  'CAPS.*.stampRadius': 'Radius of each particle’s dot (m), the same at every paint detail. A dot smaller than a paint texel paints one texel.',
  'CAPS.*.softness': 'Edge of each dot: 0 = hard, 1 = fades out to the rim.',
  'CAPS.*.rate': 'Particles per second at full pressure. More = faster coverage.',
  'CAPS.*.coneAngle': 'Spray cone half-angle (rad). Wider = bigger, softer spray.',
  'CAPS.*.color': 'Color of the cap on the can and the pickup.',
  'CAPS.*.crosshair': 'Crosshair circle diameter for this cap (px).',
  // Pressure
  'PRESSURE.drainPerSecond': 'Pressure lost per second of spraying with the small can (1 = full can).',
  'CAN_SIZES.*.drain': 'Pressure-loss multiplier for this can size. Lower = lasts longer.',
  'PRESSURE.thinThreshold': 'Below this pressure the paint gets thinner.',
  'PRESSURE.sputterThreshold': 'Below this pressure the can sputters and the HUD warns.',
  'PRESSURE.minSteadyFlow': 'Paint flow at the sputter threshold (flow ramps down to this from the thin threshold).',
  'PRESSURE.sputterDuty': 'Fraction of the time a sputtering can actually sprays.',
  'PRESSURE.shakeRestore': 'Pressure restored by one shake (RMB).',
  'PRESSURE.shakeDuration': 'Length of one shake (s).',
  // Rendering
  'RENDER.pixelScale': 'Render resolution divisor: 2 = half resolution, upscaled with chunky pixels. Higher = faster.',
  'ATMOS.rain': 'Falling rain (also its sound, lightning and drops on metal).',
  'ATMOS.rainDensity': 'Fraction of the maximum number of raindrops.',
  'ATMOS.rainSpeed': 'Fall speed of the rain (m/s).',
  'ATMOS.rainColor': 'Color of the raindrop streaks.',
  'ATMOS.rainOpacity': 'How visible the raindrops are (1 = default, 0 = invisible but still heard).',
  'ATMOS.wind': 'Wind (m/s): slants the rain and carries the smoke.',
  'ATMOS.fogDensity': 'How fast the drawing fades into paper with distance. Higher = closer haze.',
  'ATMOS.cloudBase': 'Height where everything starts fading into the low clouds (paper), in m.',
  'ATMOS.cloudFade': 'Height over which things fade fully into the clouds (m).',
  'ATMOS.wetness': 'Wet look on up-facing surfaces: darker with highlights.',
  'ATMOS.shadows': 'Moonlight shadows around the player.',
  'ATMOS.spotShadows': 'With baking off: the nearest lamps of kinds that cast shadows get real shadow maps (2 slots).',
  'ATMOS.shadowRange': 'Size of the moon shadow area around the player (m). Bigger = blurrier shadows.',
  'ATMOS.practical': 'Multiplier for all light props.',
  'ATMOS.lightBudget': 'With baking off: real lights handed to the nearest light props. Others only glow.',
  'ATMOS.emissiveBoost': 'Brightness of glowing surfaces: lamps, neon tubes.',
  'ATMOS.moonDir': 'Direction toward the moon (sun in daylight); sets shadow direction.',
  'ATMOS.lightDecay': 'Distance falloff of light props: 2 = physically correct, lower reaches farther. Rebakes the lamp light.',
  'ATMOS.moon': 'Moonlight strength.',
  'ATMOS.moonColor': 'Moonlight color.',
  'ATMOS.ambient': 'Ambient light strength (sky fill).',
  'ATMOS.ambientSky': 'Ambient light color from above.',
  'ATMOS.ambientGround': 'Ambient light color from below.',
  // Ink
  'INK.paper': 'Paper color: lit surfaces and the sky.',
  'INK.ink': 'Ink color: lines, hatching and solid black.',
  'INK.exposure': 'Light multiplier before the tone steps. Higher = more paper, less ink.',
  'INK.paperTone': 'Tones above this are bare paper; below it, hatching starts.',
  'INK.hatchTone': 'Tones below this get cross-hatching.',
  'INK.blackTone': 'Tones below this are solid ink.',
  'INK.toneNoise': 'Ragged, hand-drawn edges between the tone steps.',
  'INK.hatchPx': 'Hatch line spacing on screen, in pixels (the same at any distance).',
  'INK.hatchWidth': 'Hatch line thickness, as a fraction of the spacing.',
  'INK.grime': 'Grime on surfaces: rain streaks, stains, buffed-over patches, cracks (0 = clean).',
  'INK.voidTop': 'Height (m) below which the city sinks into black.',
  'INK.voidBottom': 'Height (m) where the void is fully black.',
  'INK.outline': 'Strength of the pen outlines on edges and silhouettes.',
  'INK.crease': 'How readily bends between faces get a line (higher = more lines).',
  'INK.outlineFade': 'Outlines thin out over this distance (m), so far detail does not turn black.',
  'INK.wobble': 'Outlines wobble by up to this many pixels: a hand-drawn look.',
  'INK.grain': 'Paper grain strength.',
  'INK.paintLight': 'Paint brightness from the light around it.',
  'INK.paintMin': 'Paint never gets darker than this, so it keeps its color in the dark.',
  'INK.paintHatch': 'Hatching drawn over paint in the dark, so it sits in the drawing.',
  'SKYLINE.litWindows': 'Fraction of punched facade windows that are lit (drawn as paper).',
  'SKYLINE.lineRange': 'How far thin lines (lattices, railings, wires) stay visible, as a multiplier. Lower = cleaner distance.',
  'SKYLINE.seed': 'Pick a different city (press rebuild city).',
  'SKYLINE.radius': 'How far the city reaches around the level (m).',
  'SKYLINE.block': 'City block size, street to street (m).',
  'SKYLINE.streetMin': 'Narrowest street (m).',
  'SKYLINE.streetMax': 'Widest street (m).',
  'SKYLINE.margin': 'Free space kept around the level (m).',
  'SKYLINE.street': 'Street height (m): how far down the canyons go.',
  'SKYLINE.near': 'Within this distance, roofs are mostly low (you look down on them), with a few huge towers.',
  'SKYLINE.tallChance': 'Share of lots that are huge towers.',
  'SKYLINE.tallMin': 'Lowest top of a huge tower (m).',
  'SKYLINE.tallMax': 'Highest top of a huge tower (m).',
  'SKYLINE.clutterRange': 'Rooftop clutter (tanks, frames, masts, railings) within this distance (m).',
  // Volumetrics + grading
  'VOLUMETRICS.enabled': 'Light shafts and glowing fog (also in the pause menu).',
  'VOLUMETRICS.downscale': 'Resolution divisor of the volumetric pass. Higher = faster, softer.',
  'VOLUMETRICS.steps': 'Samples along each view ray. More = smoother, slower.',
  'VOLUMETRICS.maxDistance': 'Rays stop after this many meters.',
  'VOLUMETRICS.density': 'How much the air scatters light. Higher = thicker light shafts.',
  'VOLUMETRICS.moon': 'Strength of moonlight shafts.',
  'VOLUMETRICS.lights': 'Strength of light-prop scattering in the fog.',
  'VOLUMETRICS.anisotropy': 'Forward scattering: 0 = glows the same from all sides, 0.9 = only when looking toward the light.',
  'GRADE.exposure': 'Overall brightness in stops (+1 = twice as bright).',
  'GRADE.contrast': 'Contrast. 1 = neutral.',
  'GRADE.saturation': 'Color saturation. 0 = gray, 1 = neutral.',
  'GRADE.temperature': 'White balance: warm (+) or cool (-).',
  'GRADE.tint': 'White balance: magenta (+) or green (-).',
  // Sound
  'AUDIO.masterGain': 'Overall volume.',
  'AUDIO.rainGain': 'Rain sound at full rain density.',
  'AUDIO.sirenGain': 'Loudness of the far-off police and fire sirens.',
  'AUDIO.rainTone': 'Brightness of the rain sound (lowpass, Hz). Lower = duller, farther.',
  'AUDIO.metalGain': 'Loudness of raindrops pinging on metal.',
  'AUDIO.metalRate': 'Drops per second on each metal piece at full rain density.',
  'AUDIO.metalRange': 'Drops on metal are heard within this distance (m).',
  'AUDIO.thunderGain': 'Thunder volume.',
  'AUDIO.ambienceGain': 'Distant city rumble.',
  'AUDIO.fanGain': 'AC fan hum when standing at the fan.',
  'AUDIO.fanRange': 'The fan hum fades out over this distance (m).',
  'AUDIO.hissGain': 'Spray can hiss.',
  'AUDIO.footstepGain': 'Footsteps.',
  // Lightning, smoke, fans, flicker
  'THUNDER.enabled': 'Random lightning and thunder while it rains.',
  'SIRENS.enabled': 'Now and then a police or fire siren passes somewhere far off in the city.',
  'SIRENS.minInterval': 'Shortest time between sirens (s).',
  'SIRENS.maxInterval': 'Longest time between sirens (s).',
  'CCTV.followRange': 'CCTV cameras start turning toward you within this distance (m), and their light comes on.',
  'CCTV.lockRange': 'Within this distance (m) they follow you fully and their light is at full strength.',
  'CCTV.maxTurn': 'How far a camera head can turn from straight out (rad). Beyond it you are behind the wall and it stops following.',
  'THUNDER.minInterval': 'Shortest time between strikes (s).',
  'THUNDER.maxInterval': 'Longest time between strikes (s).',
  'THUNDER.flashAmbient': 'Extra ambient light at the peak of a flash.',
  'THUNDER.flashMoon': 'Extra moonlight at the peak of a flash (also lights the fog).',
  'THUNDER.flashSky': 'How much the sky brightens in a flash.',
  'THUNDER.minDelay': 'Shortest delay from flash to thunder (s): the closest strikes.',
  'THUNDER.maxDelay': 'Longest delay from flash to thunder (s): far strikes are later and softer.',
  'SMOKE.enabled': 'Smoke from vents and exhausts, warm air from AC units.',
  'SMOKE.perEmitter': 'Puffs per source. All smoke is one draw call.',
  'SMOKE.life': 'Seconds a puff lives.',
  'SMOKE.rise': 'How high a puff rises over its life (m).',
  'SMOKE.drift': 'How far the wind carries the smoke.',
  'SMOKE.startSize': 'Puff size when it appears (m).',
  'SMOKE.endSize': 'Puff size when it fades (m).',
  'SMOKE.opacity': 'Smoke opacity.',
  'SMOKE.color': 'Smoke color (before lighting).',
  'FANS.speed': 'AC fan revolutions per second.',
  'FLICKER.speed': 'Random flicker steps per second.',
  'FLICKER.neonRate': 'Chance per step that a neon sign dips.',
  'FLICKER.neonDepth': 'How dark a neon dip gets.',
  'FLICKER.neonHum': 'Fast, faint brightness hum of the neon tubes.',
  // Lights
  'VIEWMODEL.fill': 'Fill light on the hands and tools (drawn in their own pass).',
  'VIEWMODEL.fillSky': 'Hand fill color from above.',
  'VIEWMODEL.fillGround': 'Hand fill color from below.',
  'VIEWMODEL.rim': 'Rim light on the hands and tools.',
  'VIEWMODEL.rimColor': 'Hand rim light color.',
  'PLAYER_LIGHT.intensity': 'Faint light around the player so dark corners stay walkable.',
  'PLAYER_LIGHT.range': 'How far the player glow reaches (m).',
  'PLAYER_LIGHT.height': 'Height of the player glow above the eyes (m). From above it reads as ambient, not a flashlight.',
  'PLAYER_LIGHT.color': 'Player glow color.',
  'LIGHTS.*.color': 'Light color. Lenses and neon tubes follow it.',
  'LIGHTS.*.offset': 'Moves the real light from its spot on the lens (m; x right, y up, z back toward the wall).',
  'LIGHTS.*.dir': 'Where the light points, relative to the prop (front is -z). Floodlight heads turn with it.',
  'LIGHTS.*.intensity': 'Light strength (scaled by "light props" in Rendering).',
  'LIGHTS.*.range': 'Distance where the light fades to nothing (m). Free on the GPU; a longer range only takes longer to bake.',
  'LIGHTS.*.spread': 'Cone half-angle (rad). 1.55 is nearly a hemisphere.',
  'LIGHTS.*.softness': 'Edge of the cone: 0 = hard, 1 = fades from the center.',
  'LIGHTS.*.glow': 'Size of the glow sprite at the lens (m). 0 = none.',
  'LIGHTS.*.glowAllAround': 'Glow shows from every side (bare bulbs) instead of only from the front of the lens.',
  'LIGHTS.*.beam': 'Length of the visible light cone (m). 0 = none.',
  'LIGHTS.*.shadows': 'This light kind casts shadows (baked, see Baked light). With baking off it may take one of the two spot shadow slots when near you.',
  'LIGHTMAP.enabled': 'Bake every lamp into light textures, with shadows: any number of lamps costs the same, at any distance. Off = the old real-light pool, for comparison.',
  'LIGHTMAP.shadows': 'Baked lamps cast shadows from walls, parapets, rails and props. Rebakes in a moment.',
  'LIGHTMAP.texelsPerMeter': 'Detail of baked light on paintable surfaces: 4 = 25 cm light texels. Higher = sharper shadows, longer bakes.',
  'LIGHTMAP.smooth': 'Blend between light texels. Off = hard, pixelated light and shadow edges.',
  'LIGHTMAP.highlights': 'The nearest lamps also add a moving wet highlight (real-time, wet surfaces only). 0 = none, cheapest.',
  'LIGHTMAP.budgetMs': 'Time per frame spent rebaking after an edit or a light tweak. Higher = faster updates, lower fps meanwhile.',
};

/** Tooltip for a config path, if there is one. */
export function hintFor(path: string[]): string | undefined {
  const keys = path.filter((k) => !/^\d+$/.test(k));
  if (keys[0] === 'DAYLIGHT') {
    const h = HINTS[['ATMOS', ...keys.slice(1)].join('.')];
    return h && `Build-mode daylight. ${h}`;
  }
  const exact = HINTS[keys.join('.')];
  if (exact) return exact;
  if (keys.length >= 3) return HINTS[[keys[0], '*', ...keys.slice(2)].join('.')];
  return undefined;
}

/** Tooltips for actions and readouts, by label. */
export const LABEL_HINTS: Record<string, string> = {
  position: 'Player feet position (x, y, z).',
  speed: 'Horizontal speed (m/s).',
  vertical: 'Vertical speed (m/s); negative = falling.',
  state: 'Grounded, airborne, crouched, on ladder or flying (build mode).',
  'STRIKE NOW': 'Trigger a lightning strike right now (thunder follows).',
  fps: 'Frames per second, and CPU time per frame.',
  'gpu: scene': 'GPU time of the main scene pass (needs timer queries; desktop Chromium).',
  'gpu: volumetrics': 'GPU time of the volumetric light pass.',
  'gpu: hands + post': 'GPU time of the hands, tools and the final grading pass.',
  'draw calls': 'Draw calls in the main scene pass. Should not grow with paint.',
  'real lights': 'Real spot lights in use: moving CCTV lights (every near lamp with baking off).',
  'baked light': 'Memory of the light textures, and time the bake took this frame.',
  bake: 'Parts of the level still waiting for their light (after an edit or a light tweak).',
  triangles: 'Triangles drawn in the main scene pass.',
  'paint tex': 'Paint textures created so far / paintable surfaces.',
  'tex memory': 'Memory used by paint textures.',
  uploads: 'Paint textures uploaded to the GPU this frame (only the rect that changed, one call each).',
  particles: 'Spray particles in flight.',
  'paint runs': 'Paint runs moving right now.',
};
