import { type LightKind, type NeonColor, DAYLIGHT, LIGHT_SPREAD_MAX, LIGHTS, NEON_COLORS } from '../config';
import { live, r, t, c, v3, type Item, type Section } from './tuning';

// F3 panel contents for the world (tuning.ts has the helpers).

const LIGHT_LABELS: Record<LightKind, string> = { wallLamp: 'WALL LAMP', floodlight: 'FLOODLIGHT', neon: 'NEON SIGNS', billboardLamp: 'BILLBOARD LAMP', lampPost: 'LAMP POST', stringLights: 'STRING LIGHTS', cctv: 'CCTV CAMERA' };

function lightItems(): Item[] {
  const fx = () => live.rebuildLights();
  const props = () => live.rebuildLightProps();
  return (Object.keys(LIGHTS) as LightKind[]).flatMap((k) => [
    { kind: 'heading', label: `LIGHT · ${LIGHT_LABELS[k]}` } as Item,
    ...(k === 'neon'
      ? (Object.keys(NEON_COLORS) as NeonColor[]).map((n) => c(`color: ${n}`, ['NEON_COLORS', n], props))
      : [c('color', ['LIGHTS', k, 'color'], props)]),
    r('color tint (0 = none)', ['LIGHTS', k, 'tint'], 0, 1, 0.05, props),
    r('intensity', ['LIGHTS', k, 'intensity'], 0, 200, 0.5),
    r('range (m)', ['LIGHTS', k, 'range'], 1, 80, 0.5, fx),
    r('spread (rad)', ['LIGHTS', k, 'spread'], 0.1, LIGHT_SPREAD_MAX, 0.01, fx),
    r('edge softness', ['LIGHTS', k, 'softness'], 0, 1, 0.05, fx),
    r('glow size', ['LIGHTS', k, 'glow'], 0, 3, 0.05, fx),
    t('glow from all sides', ['LIGHTS', k, 'glowAllAround'], fx),
    r('beam length', ['LIGHTS', k, 'beam'], 0, 20, 0.5, fx),
    t('casts shadows', ['LIGHTS', k, 'shadows']),
  ]);
}

/** DAYLIGHT overrides (build mode): numbers as sliders, hex strings as colors. */
function daylightItems(): Item[] {
  const apply = () => live.applyDaylight();
  const ranges: Record<string, [number, number, number]> = {
    fogDensity: [0, 0.05, 0.001], cloudBase: [5, 400, 5], ambient: [0, 4, 0.05], moon: [0, 6, 0.05],
    practical: [0, 4, 0.05], emissiveBoost: [0, 6, 0.1], wetness: [0, 1, 0.01],
  };
  return Object.entries(DAYLIGHT).flatMap(([k, v]): Item[] => {
    if (typeof v === 'string') return [c(k, ['DAYLIGHT', k], apply)];
    if (typeof v === 'boolean') return [t(k, ['DAYLIGHT', k], apply)];
    if (Array.isArray(v)) return v3(k, ['DAYLIGHT', k], -1, 1, 0.01, apply);
    const [min, max, step] = ranges[k] ?? [0, 10, 0.01];
    return [r(k, ['DAYLIGHT', k], min, max, step, apply)];
  });
}

/** F3 sections for the world: ink, screen + post, weather, props, city, sound, daylight, lights, performance. */
export function worldSections(): Section[] {
  const sync = () => live.syncAtmosphere();
  return [
    {
      id: 'ink',
      title: 'Ink',
      items: [
        c('paper', ['INK', 'paper']),
        c('ink', ['INK', 'ink']),
        c('sky', ['INK', 'sky']),
        c('clouds', ['INK', 'cloud']),
        r('exposure', ['INK', 'exposure'], 0.2, 5, 0.05),
        r('colored light strength', ['INK', 'tint'], 0, 1, 0.05),
        r('paper above tone', ['INK', 'paperTone'], 0, 1.5, 0.01),
        r('cross-hatch below', ['INK', 'hatchTone'], 0, 1, 0.01),
        r('solid ink below', ['INK', 'blackTone'], 0, 1, 0.01),
        r('ragged tone edges', ['INK', 'toneNoise'], 0, 0.3, 0.005),
        r('hatch spacing (px)', ['INK', 'hatchPx'], 2, 16, 0.5),
        r('hatch line width', ['INK', 'hatchWidth'], 0.05, 0.9, 0.01),
        r('grime', ['INK', 'grime'], 0, 2, 0.05),
        r('void starts (m)', ['INK', 'voidTop'], -100, 40, 1),
        r('void is black at (m)', ['INK', 'voidBottom'], -150, 20, 1),
        { kind: 'heading', label: 'OUTLINES + PAPER' },
        r('outlines', ['INK', 'outline'], 0, 2, 0.05),
        r('crease sensitivity', ['INK', 'crease'], 0, 4, 0.05),
        r('outlines thin out over (m)', ['INK', 'outlineFade'], 10, 1000, 5),
        r('paper grain', ['INK', 'grain'], 0, 3, 0.05),
        { kind: 'heading', label: 'PAINT' },
        r('opacity steps', ['PAINT', 'alphaSteps'], 0, 12, 1),
        r('paint light', ['INK', 'paintLight'], 0.2, 4, 0.05),
        r('paint darkest', ['INK', 'paintMin'], 0, 1, 0.01),
        r('hatching over paint', ['INK', 'paintHatch'], 0, 1, 0.01),
      ],
    },
    {
      id: 'post',
      title: 'Screen + post',
      items: [
        r('pixel scale', ['RENDER', 'pixelScale'], 1, 5, 0.25, () => live.applyPixelScale()),
        { kind: 'heading', label: 'VOLUMETRICS' },
        t('volumetric light', ['VOLUMETRICS', 'enabled']),
        r('resolution divisor', ['VOLUMETRICS', 'downscale'], 1, 8, 1),
        r('steps', ['VOLUMETRICS', 'steps'], 4, 32, 1),
        r('max distance', ['VOLUMETRICS', 'maxDistance'], 5, 120, 1),
        r('density', ['VOLUMETRICS', 'density'], 0, 0.2, 0.001),
        r('moon shafts', ['VOLUMETRICS', 'moon'], 0, 3, 0.05),
        r('light scatter', ['VOLUMETRICS', 'lights'], 0, 5, 0.05),
        r('forward scatter', ['VOLUMETRICS', 'anisotropy'], 0, 0.9, 0.01),
        { kind: 'heading', label: 'COLOR GRADING' },
        r('exposure (stops)', ['GRADE', 'exposure'], -3, 3, 0.05),
        { kind: 'heading', label: 'VIGNETTE' },
        r('strength', ['VIGNETTE', 'strength'], 0, 1, 0.01, () => live.syncVignette()),
        r('starts at (%)', ['VIGNETTE', 'start'], 0, 99, 1, () => live.syncVignette()),
        c('color', ['VIGNETTE', 'color'], () => live.syncVignette()),
        { kind: 'heading', label: 'HUD' },
        t('performance readout', ['HUD', 'perf']),
        t('frame', ['HUD', 'frame']),
        t('rec', ['HUD', 'rec']),
        t('camera label', ['HUD', 'cam']),
        t('clock', ['HUD', 'clock']),
        r('hotbar: size', ['HUD', 'slotSize'], 16, 60, 1),
        r('hotbar: gap', ['HUD', 'slotGap'], 0, 40, 1),
      ],
    },
    {
      id: 'city',
      title: 'City',
      items: [
        r('city opacity', ['SKYLINE', 'opacity'], 0, 1, 0.01),
        r('lit windows', ['SKYLINE', 'litWindows'], 0, 1, 0.01),
        r('thin lines visible to (x)', ['SKYLINE', 'lineRange'], 0, 3, 0.05, () => live.syncSkyline()),
        r('seed', ['SKYLINE', 'seed'], 1, 100, 1),
        r('radius (m)', ['SKYLINE', 'radius'], 100, 1200, 10),
        r('full height from (m)', ['SKYLINE', 'riseTo'], 100, 1200, 10),
        r('block pitch (m)', ['SKYLINE', 'block'], 20, 120, 1),
        r('street min (m)', ['SKYLINE', 'streetMin'], 2, 40, 0.5),
        r('street max (m)', ['SKYLINE', 'streetMax'], 2, 40, 0.5),
        r('margin round the level (m)', ['SKYLINE', 'margin'], 0, 60, 1),
        r('street height (m)', ['SKYLINE', 'street'], -300, -10, 1),
        r('near ring (m)', ['SKYLINE', 'near'], 0, 600, 5),
        r('huge tower share', ['SKYLINE', 'tallChance'], 0, 1, 0.01),
        r('huge tower min top (m)', ['SKYLINE', 'tallMin'], -50, 300, 1),
        r('huge tower max top (m)', ['SKYLINE', 'tallMax'], -50, 400, 1),
        r('rooftop clutter range (m)', ['SKYLINE', 'clutterRange'], 0, 800, 10),
        { kind: 'action', label: 'rebuild city', run: () => live.rebuildCity() },
      ],
    },
    {
      id: 'sound',
      title: 'Sound',
      items: [
        r('master', ['AUDIO', 'masterGain'], 0, 1.5, 0.01),
        r('rain', ['AUDIO', 'rainGain'], 0, 0.5, 0.005),
        r('rain brightness (Hz)', ['AUDIO', 'rainTone'], 500, 9000, 50),
        r('drops on metal', ['AUDIO', 'metalGain'], 0, 0.4, 0.005),
        r('drops on metal / s per piece', ['AUDIO', 'metalRate'], 0, 10, 0.1),
        r('drops on metal heard within (m)', ['AUDIO', 'metalRange'], 1, 20, 0.5),
        r('thunder', ['AUDIO', 'thunderGain'], 0, 1.5, 0.01),
        r('city ambience', ['AUDIO', 'ambienceGain'], 0, 0.3, 0.005),
        r('AC fan hum', ['AUDIO', 'fanGain'], 0, 0.5, 0.005),
        r('fan heard within (m)', ['AUDIO', 'fanRange'], 1, 20, 0.5),
        r('spray hiss', ['AUDIO', 'hissGain'], 0, 0.8, 0.01),
        r('footsteps', ['AUDIO', 'footstepGain'], 0, 1, 0.01),
      ],
    },
    {
      id: 'weather',
      title: 'Weather',
      items: [
        t('rain', ['ATMOS', 'rain']),
        r('rain density', ['ATMOS', 'rainDensity'], 0, 1, 0.01),
        r('rain speed', ['ATMOS', 'rainSpeed'], 4, 30, 0.5),
        c('rain color', ['ATMOS', 'rainColor']),
        r('rain opacity', ['ATMOS', 'rainOpacity'], 0, 4, 0.05),
        ...v3('wind', ['ATMOS', 'wind'], -5, 5, 0.1),
        r('fade into paper (1/m)', ['ATMOS', 'fogDensity'], 0, 0.03, 0.0005),
        r('cloud base', ['ATMOS', 'cloudBase'], 5, 80, 1),
        r('cloud fade', ['ATMOS', 'cloudFade'], 2, 120, 1),
        r('wetness', ['ATMOS', 'wetness'], 0, 1, 0.01),
        { kind: 'heading', label: 'LIGHTNING' },
        t('lightning + thunder', ['THUNDER', 'enabled']),
        { kind: 'action', label: 'STRIKE NOW', run: () => live.strikeLightning() },
        r('min seconds between', ['THUNDER', 'minInterval'], 5, 300, 1),
        r('max seconds between', ['THUNDER', 'maxInterval'], 5, 600, 1),
        r('flash: ambient', ['THUNDER', 'flashAmbient'], 0, 20, 0.5),
        r('flash: moon', ['THUNDER', 'flashMoon'], 0, 20, 0.5),
        r('flash: sky', ['THUNDER', 'flashSky'], 0, 2, 0.05),
        r('thunder delay min (s)', ['THUNDER', 'minDelay'], 0, 5, 0.1),
        r('thunder delay max (s)', ['THUNDER', 'maxDelay'], 0, 10, 0.1),
      ],
    },
    {
      id: 'props',
      title: 'Props',
      items: [
        { kind: 'heading', label: 'CCTV CAMERAS' },
        r('start following within (m)', ['CCTV', 'followRange'], 1, 30, 0.5),
        r('follow fully within (m)', ['CCTV', 'lockRange'], 0, 20, 0.5),
        r('max head turn (rad)', ['CCTV', 'maxTurn'], 0.2, 1.57, 0.01),
        { kind: 'heading', label: 'SMOKE (EXHAUST PIPES)' },
        t('smoke', ['SMOKE', 'enabled']),
        r('puffs per source', ['SMOKE', 'perEmitter'], 0, 48, 1),
        r('life (s)', ['SMOKE', 'life'], 0.5, 12, 0.1),
        r('rise (m)', ['SMOKE', 'rise'], 0, 8, 0.1),
        r('wind drift', ['SMOKE', 'drift'], 0, 3, 0.05),
        r('start size (m)', ['SMOKE', 'startSize'], 0.02, 1, 0.01),
        r('end size (m)', ['SMOKE', 'endSize'], 0.1, 4, 0.05),
        r('opacity', ['SMOKE', 'opacity'], 0, 1, 0.01),
        c('color', ['SMOKE', 'color']),
        { kind: 'heading', label: 'AC FANS' },
        r('revolutions / s', ['FANS', 'speed'], 0, 15, 0.1),
        { kind: 'heading', label: 'FLICKER' },
        r('steps / s', ['FLICKER', 'speed'], 1, 40, 1),
        r('neon: dip chance', ['FLICKER', 'neonRate'], 0, 0.5, 0.005),
        r('neon: dip depth', ['FLICKER', 'neonDepth'], 0, 1, 0.01),
        r('neon: hum', ['FLICKER', 'neonHum'], 0, 0.3, 0.005),
      ],
    },
    {
      id: 'daylight',
      title: 'Build-mode daylight',
      items: daylightItems(),
    },
    {
      id: 'lights',
      title: 'Lights',
      items: [
        r('falloff (2 = physical)', ['ATMOS', 'lightDecay'], 0.5, 2.5, 0.05),
        t('moon shadows', ['ATMOS', 'shadows']),
        t('spot light shadows (bake off)', ['ATMOS', 'spotShadows']),
        r('shadow range', ['ATMOS', 'shadowRange'], 8, 60, 1),
        r('shadow detail', ['ATMOS', 'shadowDetail'], 512, 4096, 512),
        r('light props', ['ATMOS', 'practical'], 0, 4, 0.05),
        r('real light budget (bake off)', ['ATMOS', 'lightBudget'], 0, 8, 1),
        r('emissive boost', ['ATMOS', 'emissiveBoost'], 0, 6, 0.1),
        { kind: 'heading', label: 'BAKED LIGHT' },
        t('bake lamp light', ['LIGHTMAP', 'enabled']),
        t('shadows', ['LIGHTMAP', 'shadows']),
        r('light texels per meter', ['LIGHTMAP', 'texelsPerMeter'], 1, 16, 1),
        r('wet highlights (nearest lamps)', ['LIGHTMAP', 'highlights'], 0, 4, 1),
        r('bake time per frame (ms)', ['LIGHTMAP', 'budgetMs'], 0.5, 16, 0.5),
        { kind: 'readout', label: 'bake', get: () => (live.stats.bakePending ? `${live.stats.bakePending} parts left` : 'done') },
        { kind: 'heading', label: 'MOONLIGHT' },
        r('intensity', ['ATMOS', 'moon'], 0, 6, 0.05),
        c('color', ['ATMOS', 'moonColor'], sync),
        ...v3('moon direction', ['ATMOS', 'moonDir'], -1, 1, 0.01, sync),
        { kind: 'heading', label: 'AMBIENT' },
        r('intensity', ['ATMOS', 'ambient'], 0, 4, 0.05),
        c('sky color', ['ATMOS', 'ambientSky'], sync),
        c('ground color', ['ATMOS', 'ambientGround'], sync),
        { kind: 'heading', label: 'HANDS (VIEW MODEL)' },
        r('fill', ['VIEWMODEL', 'fill'], 0, 4, 0.05),
        c('fill from above', ['VIEWMODEL', 'fillSky']),
        c('fill from below', ['VIEWMODEL', 'fillGround']),
        r('rim', ['VIEWMODEL', 'rim'], 0, 4, 0.05),
        c('rim color', ['VIEWMODEL', 'rimColor']),
        { kind: 'heading', label: 'PLAYER GLOW' },
        r('intensity', ['PLAYER_LIGHT', 'intensity'], 0, 4, 0.05),
        r('range (m)', ['PLAYER_LIGHT', 'range'], 1, 15, 0.5),
        r('height above eyes', ['PLAYER_LIGHT', 'height'], 0, 1.5, 0.05),
        c('color', ['PLAYER_LIGHT', 'color']),
        ...lightItems(),
      ],
    },
    {
      id: 'performance',
      title: 'Performance',
      open: true,
      items: [
        { kind: 'readout', label: 'fps', get: () => `${live.stats.fps.toFixed(0)}  (${live.stats.frameMs.toFixed(1)} ms cpu)` },
        { kind: 'readout', label: 'gpu: scene', get: () => live.gpu('scene') },
        { kind: 'readout', label: 'gpu: volumetrics', get: () => live.gpu('volumetrics') },
        { kind: 'readout', label: 'gpu: hands + post', get: () => live.gpu('post') },
        { kind: 'readout', label: 'draw calls', get: () => `${live.stats.drawCalls}` },
        { kind: 'readout', label: 'real lights', get: () => `${live.stats.lights}` },
        { kind: 'readout', label: 'baked light', get: () => `${(live.stats.bakedBytes / 1048576).toFixed(2)} MB, ${live.stats.bakeMs.toFixed(1)} ms` },
        { kind: 'readout', label: 'triangles', get: () => `${live.stats.triangles}` },
        { kind: 'readout', label: 'paint tex', get: () => `${live.stats.textures} / ${live.stats.surfaces} surfaces` },
        { kind: 'readout', label: 'tex memory', get: () => `${(live.stats.textureBytes / 1048576).toFixed(2)} MB` },
        { kind: 'readout', label: 'paint ops / s', get: () => `${live.stats.paintOps.toFixed(0)}` },
        { kind: 'readout', label: 'uploads', get: () => `${live.stats.uploads} rects, ${(live.stats.uploadBytes / 1024).toFixed(1)} KB` },
        { kind: 'readout', label: 'particles', get: () => `${live.stats.particles}` },
        { kind: 'readout', label: 'paint runs', get: () => `${live.stats.drips}` },
      ],
    },
  ];
}
